In [6]:
pwd

'C:\\Users\\User\\Desktop\\My-Python-Project\\Python-World-Bank-Data-Analysis'

# IMPORT RELEVANT LIBRARIES

In [7]:
import pandas as pd
import numpy as np
from scipy import stats

In [18]:
%pip install scipy

Collecting scipy
  Downloading scipy-1.18.0-cp313-cp313-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: numpy<2.8,>=2.0.0 in C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scipy) (2.5.2)
Downloading scipy-1.18.0-cp313-cp313-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
    --------------------------------------- 0.5/36.6 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.0/36.6 MB 1.6 MB/s eta 0:00:22
   -- ------------------------------------- 2.1/36.6 MB 2.5 MB/s eta 0:00:14
   -- ------------------------------------- 2.1/36.6 MB 2.5 MB/s eta 0:00:14
   ---- ----------------------------------- 4.2/36.6 MB 3.8 MB/s eta 0:00:09
   ----- ---------------------------------- 4.7/36.6 MB 3.3 MB/s eta 0:00:10
   ----- ---------------------------------- 5.0/36.6 MB 3.5 MB/s eta 0:00:10
   ------- -------------------------------- 7.1/36.6 MB 4.0 MB/s eta 0:00:08
   -------- ------------------------------- 8.1/36.6 MB 4.0 MB/s eta 0:00:08
   --------- ------------------------------ 8.9/36.6 MB 4.0 MB/s eta 0:00:07
   ---------- ----------------------------- 10.0/36.6 MB 4.1 MB/s eta 0:00:07
   ----------- ---------------------------- 10.7/36.6 MB 4.2 MB/s eta 0:00:07
   ------------- -------------------------- 12.1/36.6 MB 4.3 MB/s eta 0:00:06
   -------------- ------------------------- 13.1/36.6 MB 4.3 MB/s eta 0:00:06
   --------------- ------------------------ 14.4/36.6 MB 4.4 MB/s eta 0:00:06
   ---------------- ----------------------- 15.5/36.6 MB 4.4 MB/s eta 0:00:05
   ------------------ --------------------- 16.5/36.6 MB 4.5 MB/s eta 0:00:05
   ------------------- -------------------- 17.6/36.6 MB 4.5 MB/s eta 0:00:05
   -------------------- ------------------- 18.9/36.6 MB 4.6 MB/s eta 0:00:04
   --------------------- ------------------ 19.7/36.6 MB 4.5 MB/s eta 0:00:04
   --------------------- ------------------ 19.7/36.6 MB 4.5 MB/s eta 0:00:04
   ----------------------- ---------------- 21.8/36.6 MB 4.6 MB/s eta 0:00:04
   ------------------------ --------------- 22.5/36.6 MB 4.6 MB/s eta 0:00:04
   ------------------------- -------------- 23.6/36.6 MB 4.5 MB/s eta 0:00:03
   -------------------------- ------------- 24.4/36.6 MB 4.5 MB/s eta 0:00:03
   --------------------------- ------------ 25.4/36.6 MB 4.5 MB/s eta 0:00:03
   ---------------------------- ----------- 26.2/36.6 MB 4.5 MB/s eta 0:00:03
   ----------------------------- ---------- 27.3/36.6 MB 4.5 MB/s eta 0:00:03
   ------------------------------ --------- 27.5/36.6 MB 4.5 MB/s eta 0:00:03
   ------------------------------ --------- 28.0/36.6 MB 4.4 MB/s eta 0:00:02
   -------------------------------- ------- 29.4/36.6 MB 4.5 MB/s eta 0:00:02
   -------------------------------- ------- 30.1/36.6 MB 4.4 MB/s eta 0:00:02
   --------------------------------- ------ 30.7/36.6 MB 4.3 MB/s eta 0:00:02
   ---------------------------------- ----- 31.5/36.6 MB 4.3 MB/s eta 0:00:02
   ----------------------------------- ---- 32.2/36.6 MB 4.3 MB/s eta 0:00:02
   ----------------------------------- ---- 32.8/36.6 MB 4.2 MB/s eta 0:00:01
   ------------------------------------ --- 33.6/36.6 MB 4.2 MB/s eta 0:00:01
   ------------------------------------- -- 34.1/36.6 MB 4.2 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/36.6 MB 4.1 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/36.6 MB 4.1 MB/s eta 0:00:01
   -------------------------------------- - 35.1/36.6 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  35.9/36.6 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 3.9 MB/s  0:00:09
Installing collected packages: scipy
Successfully installed scipy-1.18.0
Note: you may need to restart the kernel to use updated packages.

# LOADING THE EDUCATION STATISTICS DATASET INTO DATAFRAME

In [12]:
edu_data = pd.read_csv('data/WB_EDSTATS_WIDEF.csv', sep=';', low_memory = False)

In [13]:
edu_data

,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,SEX_LABEL,AGE,AGE_LABEL,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,A,Annual,ABW,Aruba,WB_EDSTATS_UIS_AIR_1_GLAST_GPIA,Gross intake ratio to the last grade of primar...,_T,Total,_T,All age ranges or no breakdown by age,...,NaN,NaN,1.09103,1.00726,NaN,NaN,NaN,NaN,NaN,NaN
1,A,Annual,ABW,Aruba,WB_EDSTATS_UIS_AIR_2_GPV_GLAST_GPIA,Gross intake ratio to the last grade of lower ...,_T,Total,_T,All age ranges or no breakdown by age,...,NaN,NaN,1.09480,1.07195,NaN,NaN,NaN,NaN,NaN,NaN
2,A,Annual,ABW,Aruba,WB_EDSTATS_UIS_EA_1,UIS: Percentage of population age 25+ whose hi...,F,Female,Y25T99,25-99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,Annual,ABW,Aruba,WB_EDSTATS_UIS_EA_1,UIS: Percentage of population age 25+ whose hi...,M,Male,Y25T99,25-99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A,Annual,ABW,Aruba,WB_EDSTATS_UIS_EA_1,UIS: Percentage of population age 25+ whose hi...,_T,Total,Y25T99,25-99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31897,A,Annual,ZWE,Zimbabwe,WB_EDSTATS_UIS_ONTRACK_THREE_DOMAINS_GPIA,Proportion of children aged 24-59 months who a...,_T,Total,_T,All age ranges or no breakdown by age,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.07347,NaN
31898,A,Annual,ZWE,Zimbabwe,WB_EDSTATS_UIS_READ_PRIMARY_GPIA,Proportion of students at the end of primary a...,_T,Total,_T,All age ranges or no breakdown by age,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31899,A,Annual,ZWE,Zimbabwe,WB_EDSTATS_UIS_READ_PRIMARY_LPIA,Proportion of students at the end of primary e...,_T,Total,_T,All age ranges or no breakdown by age,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31900,A,Annual,ZWE,Zimbabwe,WB_EDSTATS_UIS_MATH_PRIMARY_WPIA,Proportion of students at the end of primary a...,_T,Total,_T,All age ranges or no breakdown by age,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31901,A,Annual,ZWE,Zimbabwe,WB_EDSTATS_UIS_READ_PRIMARY_WPIA,Proportion of students at the end of primary e...,_T,Total,_T,All age ranges or no breakdown by age,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# LOADING THE WORLD DEVELOPMENT INDICATORS DATASET INTO DATAFRAME

In [14]:
wdi_data = pd.read_csv('data/WB_WDI_WIDEF.csv', sep=';', low_memory = False)

In [15]:
wdi_data

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,TTO,WB_WDI_SP_POP_3034_FE_5Y,F,Y30T34,_T,PT_W,...,9.267500e+00,9.201003e+00,9.078812e+00,8.870733e+00,8.557896e+00,8.226574e+00,7.907577e+00,7.608676e+00,7.339623e+00,7.100451e+00
1,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,TUN,WB_WDI_NY_GDP_FCST_CD,_T,_T,_T,USD,...,4.091548e+10,3.916054e+10,3.971284e+10,3.894851e+10,3.913222e+10,4.376674e+10,4.396523e+10,4.611349e+10,4.879174e+10,5.459521e+10
2,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,CAF,WB_WDI_FM_LBL_BMNY_IR_ZS,_T,_T,_T,PT,...,1.918495e+00,1.427814e+00,1.706637e+00,1.819966e+00,1.672552e+00,1.777917e+00,2.093590e+00,NaN,NaN,NaN
3,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,GUY,WB_WDI_ST_INT_ARVL,_T,_T,_T,ARRVL,...,2.350000e+05,2.470000e+05,2.870000e+05,3.150000e+05,8.640000e+04,NaN,NaN,NaN,NaN,NaN
4,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,GRC,WB_WDI_SP_POP_TOTL_MA_ZS,M,_T,_T,PT,...,4.827941e+01,4.830447e+01,4.833861e+01,4.841280e+01,4.846244e+01,4.844746e+01,4.843153e+01,4.843542e+01,4.843882e+01,4.845486e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292008,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,PRY,WB_WDI_IC_BRE_FS_P3,_T,_T,_T,IX_0T100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.403333e+01,NaN
292009,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,TLA,WB_WDI_IC_FRM_CDP_ZS,_T,_T,_T,PT_F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.753204e+01
292010,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,CSS,WB_WDI_IC_FRM_CRDC_PT_ZS,_T,_T,_T,PT_F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.195357e+01
292011,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,SVK,WB_WDI_IC_BRE_DR_P2,_T,_T,_T,IX_0T100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.523724e+01,NaN
292012,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,BRN,WB_WDI_IC_FRM_BNKS_ZS,_T,_T,_T,PT_F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.589130e+01

# VOLUME AND VARIETY OF THE EDUCATION STATISTICS DATASET

In [16]:
edu_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 31902 entries, 0 to 31901
Data columns (total 77 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   FREQ                    31902 non-null  str
 1   FREQ_LABEL              31902 non-null  str
 2   REF_AREA                31902 non-null  str
 3   REF_AREA_LABEL          31902 non-null  str
 4   INDICATOR               31902 non-null  str
 5   INDICATOR_LABEL         31902 non-null  str
 6   SEX                     31902 non-null  str
 7   SEX_LABEL               31902 non-null  str
 8   AGE                     31902 non-null  str
 9   AGE_LABEL               31902 non-null  str
 10  URBANISATION            31902 non-null  str
 11  URBANISATION_LABEL      31902 non-null  str
 12  UNIT_MEASURE            31902 non-null  str
 13  UNIT_MEASURE_LABEL      31902 non-null  str
 14  COMP_BREAKDOWN_1        31902 non-null  str
 15  COMP_BREAKDOWN_1_LABEL  31902 non-null  str
 16  AGG_METHOD              31902 non-null  str
 17  AGG_METHOD_LABEL        31902 non-null  str
 18  DATABASE_ID             31902 non-null  str
 19  DATABASE_ID_LABEL       31902 non-null  str
 20  UNIT_MULT               31902 non-null  int64
 21  UNIT_MULT_LABEL         31902 non-null  str
 22  OBS_STATUS              31902 non-null  str
 23  OBS_STATUS_LABEL        31902 non-null  str
 24  OBS_CONF                31902 non-null  str
 25  OBS_CONF_LABEL          31902 non-null  str
 26  1970                    2317 non-null   float64
 27  1971                    3219 non-null   float64
 28  1972                    2930 non-null   float64
 29  1973                    2885 non-null   float64
 30  1974                    2926 non-null   float64
 31  1975                    3132 non-null   float64
 32  1976                    3311 non-null   float64
 33  1977                    3094 non-null   float64
 34  1978                    3111 non-null   float64
 35  1979                    3220 non-null   float64
 36  1980                    3852 non-null   float64
 37  1981                    3810 non-null   float64
 38  1982                    3311 non-null   float64
 39  1983                    3315 non-null   float64
 40  1984                    3428 non-null   float64
 41  1985                    3416 non-null   float64
 42  1986                    3647 non-null   float64
 43  1987                    3358 non-null   float64
 44  1988                    3375 non-null   float64
 45  1989                    3503 non-null   float64
 46  1990                    3836 non-null   float64
 47  1991                    4163 non-null   float64
 48  1992                    3711 non-null   float64
 49  1993                    3697 non-null   float64
 50  1994                    3939 non-null   float64
 51  1995                    4105 non-null   float64
 52  1996                    4046 non-null   float64
 53  1997                    4308 non-null   float64
 54  1998                    5885 non-null   float64
 55  1999                    8495 non-null   float64
 56  2000                    9756 non-null   float64
 57  2001                    9582 non-null   float64
 58  2002                    9208 non-null   str
 59  2003                    9335 non-null   float64
 60  2004                    9770 non-null   float64
 61  2005                    10064 non-null  float64
 62  2006                    11518 non-null  float64
 63  2007                    11453 non-null  float64
 64  2008                    11363 non-null  float64
 65  2009                    12091 non-null  float64
 66  2010                    12270 non-null  float64
 67  2011                    13260 non-null  float64
 68  2012                    13163 non-null  float64
 69  2013                    12327 non-null  float64
 70  2014                    14577 non-null  float64
 71  2015                    15799 non-null  float64
 72  2016                    15276 non-null  float64
 73  2017                    13289 non-null  float64
 74  2018                    13240 non-null  float64
 75  2019                    6746 non-null   float64
 76  2020                    933 non-null    float64
dtypes: float64(50), int64(1), str(26)
memory usage: 18.7 MB

# VOLUME AND VARIETY FOR WORLD DEVELOPMENT INDICATORS DATASET

In [17]:
wdi_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 292013 entries, 0 to 292012
Columns: 105 entries, STRUCTURE to 2025
dtypes: float64(66), int64(2), str(37)
memory usage: 233.9 MB

# DESCRIPTIVE STATISTICS FOR THE EDUCATION STATISTICS DATASET

In [6]:
edu_data.describe()

,UNIT_MULT,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
count,31902.0,2.317000e+03,3.219000e+03,2.930000e+03,2.885000e+03,2.926000e+03,3.132000e+03,3.311000e+03,3.094000e+03,3.111000e+03,...,1.326000e+04,1.316300e+04,1.232700e+04,1.457700e+04,1.579900e+04,1.527600e+04,1.328900e+04,1.324000e+04,6.746000e+03,933.000000
mean,0.0,1.242267e+06,1.020247e+06,1.192988e+06,1.451595e+06,1.560643e+06,3.373234e+06,4.288556e+06,4.724934e+06,4.764519e+06,...,1.670407e+06,1.656923e+06,1.791453e+06,1.519440e+06,1.394947e+06,1.444587e+06,1.686820e+06,1.730853e+06,3.121277e+06,1053.409226
std,0.0,1.041555e+07,9.244424e+06,1.011167e+07,1.145652e+07,1.194007e+07,2.652168e+07,3.083467e+07,3.256164e+07,3.278886e+07,...,1.732063e+07,1.717232e+07,1.785847e+07,1.636699e+07,1.564394e+07,1.589372e+07,1.710991e+07,1.726296e+07,2.390567e+07,2480.218175
min,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,0.0,9.723600e-01,8.045150e-01,8.437125e-01,8.542300e-01,8.589925e-01,8.766675e-01,8.602300e-01,8.807700e-01,8.780400e-01,...,9.729200e-01,9.666100e-01,9.883450e-01,9.831100e-01,9.782500e-01,9.930175e-01,9.922100e-01,9.891150e-01,9.990300e-01,6.000000
50%,0.0,1.677248e+01,1.374610e+00,1.151560e+00,1.131890e+00,1.180745e+00,1.726865e+00,1.281790e+00,1.113240e+00,1.128600e+00,...,1.103950e+00,1.089250e+00,1.130190e+00,1.161760e+00,1.117390e+00,1.270270e+00,1.169830e+00,1.119190e+00,1.265455e+00,12.000000
75%,0.0,1.969000e+03,1.970000e+03,1.972000e+03,2.036000e+03,2.364500e+03,1.975000e+03,2.608500e+03,5.216750e+03,5.130223e+03,...,4.920484e+01,5.691488e+01,5.485090e+01,4.440153e+01,4.336874e+01,5.475434e+01,5.960000e+01,6.164931e+01,9.254859e+01,2020.000000
max,0.0,2.269336e+08,2.332577e+08,2.410833e+08,2.543370e+08,2.631708e+08,5.260186e+08,5.864742e+08,5.964270e+08,6.010179e+08,...,5.326514e+08,5.313093e+08,5.342557e+08,5.276980e+08,5.218075e+08,5.179396e+08,5.188967e+08,5.177084e+08,5.151576e+08,47449.000000

# DESCRIPTIVE STATISTICS FOR THE WORLD DEVELOPMENT INDICATORS DATASET

In [12]:
wdi_data.describe()

,DECIMALS,UNIT_MULT,1960,1961,1962,1963,1964,1965,1966,1967,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
count,292013.0,292013.000000,3.722500e+04,4.255900e+04,4.384600e+04,4.477600e+04,4.528200e+04,4.709500e+04,4.735300e+04,4.799000e+04,...,2.254340e+05,2.233250e+05,2.224450e+05,2.195330e+05,2.169980e+05,2.114630e+05,1.979830e+05,1.840840e+05,1.490940e+05,7.874200e+04
mean,2.0,0.036759,1.867861e+12,1.739282e+12,1.783771e+12,1.852484e+12,2.005766e+12,2.238030e+12,2.436783e+12,2.702994e+12,...,5.850071e+12,6.241593e+12,6.506594e+12,3.133416e+13,3.829931e+14,2.049221e+15,1.558939e+16,5.945487e+16,1.633987e+17,5.348218e+13
std,0.0,0.511238,9.560194e+13,9.646743e+13,1.013865e+14,1.072446e+14,1.161293e+14,1.328351e+14,1.461519e+14,1.629627e+14,...,4.003680e+14,4.220996e+14,4.091638e+14,1.151367e+16,1.748475e+17,9.378734e+17,6.930717e+18,2.550174e+19,6.308288e+19,2.819047e+15
min,2.0,0.000000,-6.983892e+14,-1.048260e+15,-1.190074e+15,-1.321699e+15,-1.403476e+15,-1.815444e+15,-2.305316e+15,-2.572435e+15,...,-3.970130e+14,-4.306058e+14,-4.421837e+14,-3.551874e+15,-6.131892e+15,-4.608969e+14,-5.290986e+14,-3.846495e+15,-4.178515e+17,-2.352286e+16
25%,2.0,0.000000,4.509557e+00,4.571205e+00,4.631375e+00,4.725975e+00,4.806221e+00,4.555201e+00,4.826756e+00,4.800054e+00,...,5.119784e+00,5.555556e+00,5.067327e+00,5.265444e+00,5.202782e+00,5.743786e+00,5.726216e+00,5.885859e+00,6.000000e+00,6.514694e+00
50%,2.0,0.000000,3.710000e+01,3.796100e+01,3.681804e+01,3.645330e+01,3.736858e+01,3.738654e+01,4.008900e+01,4.089182e+01,...,3.890000e+01,4.162500e+01,3.899578e+01,3.998100e+01,4.073958e+01,4.141181e+01,4.296900e+01,4.558718e+01,4.623425e+01,4.006237e+01
75%,2.0,0.000000,9.408000e+04,8.150450e+04,7.330000e+04,7.232200e+04,8.443525e+04,1.191495e+05,1.560000e+05,2.018285e+05,...,6.456573e+03,9.001201e+03,8.825400e+03,1.113400e+04,1.130449e+04,1.290200e+04,1.530850e+04,2.986970e+04,2.322700e+04,1.100086e+06
max,2.0,9.000000,7.617957e+15,8.409533e+15,9.074665e+15,9.713710e+15,1.053697e+16,1.233202e+16,1.375050e+16,1.529781e+16,...,7.248544e+16,7.646208e+16,7.002421e+16,5.391345e+18,8.144900e+19,4.312820e+20,3.083842e+21,1.094152e+22,2.435800e+22,2.928519e+17

# UNPIVOTING THE EDUCATION STATISTICS DATASET

# MANUAL MEAN CALCULATION FOR THE EDUCATION STATISTICS DATASET - YR 2015

In [41]:
mean_value = np.nanmean(edu_data['2015']) #using NumPy

print(mean_value)

1394947.0210586253

# MANUAL MEDIAN CALCULATION FOR THE EDUCATION STATISTICS DATASET - YR 2020

In [9]:
median_value = np.nanmedian(edu_data['2020'])

print(median_value)

12.0

# MANUAL MEAN CALCULATION FOR THE WORLD DEVELOPMENT INDICATORS DATASET - YR 2015

In [42]:
mean_value = np.nanmean(wdi_data['2015'])

print(mean_value)

5189685619819.015

# MANUAL MEDIAN CALCULATION FOR THE WORLD DEVELOPMENT INDICATORS DATASET - YR 2020

In [10]:
median_value = np.nanmedian(wdi_data['2020'])

print(median_value)

40.739581013542654

# IDENTIFYING MISSING VALUES IN THE EDUCATION STATISTICS DATASET

In [11]:
print(edu_data.isna().sum())

FREQ                  0
FREQ_LABEL            0
REF_AREA              0
REF_AREA_LABEL        0
INDICATOR             0
                  ...
2016              16626
2017              18613
2018              18662
2019              25156
2020              30969
Length: 77, dtype: int64

# IDENTIFYING MISSING VALUES IN THE WORLD DEVELOPMENT INDICATORS STATISTICS DATASET

In [12]:
print(wdi_data.isna().sum())

STRUCTURE            0
STRUCTURE_ID         0
ACTION               0
FREQ                 0
REF_AREA             0
                 ...
2021             80550
2022             94030
2023            107929
2024            142919
2025            213271
Length: 105, dtype: int64

# GROUP-BASED MEDIAN ATTRIBUTE - FILLING MISSING VALUES WITH MEDIAN VALUES

In [45]:
year_columns = ['2015','2016','2017','2018','2019','2020']

edu_data[year_columns] = edu_data.groupby('INDICATOR')[year_columns].transform(lambda group: group.fillna(group.median()))

In [50]:
year_columns = ['2015','2016','2017','2018','2019','2020']

wdi_data[year_columns] = wdi_data.groupby('INDICATOR')[year_columns].transform(lambda group: group.fillna(group.median()))